/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CompanyRole.ManageBranch;

/**
 *
 * @author JANFAN
 */
import Business.Business;
import Business.Food.Food;
import Business.Food.FoodCombo;
import Business.Organization.Branch;
import Business.Organization.Company;
import Business.Organization.Farm;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

public class CreateBranchJPanel extends javax.swing.JPanel {

           /**
            * Creates new form CreateBranchJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Company company;
           JSplitPane SplitPanel;

           public CreateBranchJPanel(JPanel userProcessContainer, Business business, Company company, JSplitPane SplitPanel) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.company = company;
                      this.SplitPanel = SplitPanel;
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      btnBack = new javax.swing.JButton();
                      jLabel1 = new javax.swing.JLabel();
                      jLabel2 = new javax.swing.JLabel();
                      jLabel3 = new javax.swing.JLabel();
                      jLabel4 = new javax.swing.JLabel();
                      jLabel5 = new javax.swing.JLabel();
                      jLabel6 = new javax.swing.JLabel();
                      jLabel7 = new javax.swing.JLabel();
                      txtName = new javax.swing.JTextField();
                      txtUserName = new javax.swing.JTextField();
                      txtPassword = new javax.swing.JTextField();
                      txtPostcode = new javax.swing.JTextField();
                      txtLocation = new javax.swing.JTextField();
                      txtCountry = new javax.swing.JTextField();
                      btnCreate = new javax.swing.JButton();

                      setBackground(new java.awt.Color(243, 222, 186));

                      btnBack.setBackground(new java.awt.Color(169, 144, 126));
                      btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnBack.setForeground(new java.awt.Color(255, 255, 255));
                      btnBack.setText("<< BACK");
                      btnBack.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnBackActionPerformed(evt);
                                 }
                      });

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("CREATE BRANCH");

                      jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel2.setText("Name");

                      jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel3.setText("Username");

                      jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel4.setText("Password");

                      jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel5.setText("Country");

                      jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel6.setText("Location");

                      jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel7.setText("Postcode");

                      txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      txtUserName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      txtPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      txtPostcode.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtPostcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      txtLocation.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      txtCountry.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtCountry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      btnCreate.setBackground(new java.awt.Color(103, 93, 80));
                      btnCreate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnCreate.setForeground(new java.awt.Color(255, 255, 255));
                      btnCreate.setText("CREATE");
                      btnCreate.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnCreateActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGap(28, 28, 28)
                                                                  .addComponent(btnBack))
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGap(273, 273, 273)
                                                                  .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGap(145, 145, 145)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                             .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                  .addGap(31, 31, 31)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addContainerGap(216, Short.MAX_VALUE))
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnBack)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                  .addComponent(jLabel2)
                                                                  .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGap(48, 48, 48)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                             .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(jLabel3))
                                                                  .addGap(18, 18, 18)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                             .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(jLabel4))
                                                                  .addGap(18, 18, 18)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                             .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(jLabel5))
                                                                  .addGap(18, 18, 18)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                             .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(jLabel6))
                                                                  .addGap(18, 18, 18)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                             .addComponent(txtPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(jLabel7))))
                                            .addGap(47, 47, 47)
                                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(107, 107, 107))
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
               // TODO add your handling code here:
               ManageBranchJPanel Panel = new ManageBranchJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnBackActionPerformed

           private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
                      // TODO add your handling code here:
                      if (txtName.getText().isEmpty() || txtUserName.getText().isEmpty() || txtPassword.getText().isEmpty()
                                          || txtCountry.getText().isEmpty() || txtLocation.getText().isEmpty() || txtPostcode.getText().isEmpty()) {
                                 JOptionPane.showMessageDialog(this, "The branch information hasn't completed it. ");
                      } else {
                                 String Name = txtName.getText();
                                 String Username = txtUserName.getText();
                                 String Password = txtPassword.getText();
                                 String Nation = txtCountry.getText();
                                 String Location = txtLocation.getText();
                                 int Postcode = Integer.parseInt(txtPostcode.getText());
                                 Branch branch = new Branch(Name, Username, Password, 0, Nation, Location, Postcode, company);
                                 company.getBranchList().add(branch);
                                 business.getBranchList().add(branch);
                                 business.getAccountList().add(branch);
                                 for (Map.Entry<Food, Double> set
                                                     : company.getMenu().entrySet()) {
                                            FoodCombo fc = new FoodCombo(set.getKey(), 0);
                                            branch.getStock().add(fc);
                                 }
                                 JOptionPane.showMessageDialog(this, "Create branch successfully.");
                                 ManageBranchJPanel Panel = new ManageBranchJPanel(userProcessContainer, business, company, SplitPanel);
                                 SplitPanel.setRightComponent(Panel);
                      }
           }//GEN-LAST:event_btnCreateActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton btnBack;
           private javax.swing.JButton btnCreate;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel2;
           private javax.swing.JLabel jLabel3;
           private javax.swing.JLabel jLabel4;
           private javax.swing.JLabel jLabel5;
           private javax.swing.JLabel jLabel6;
           private javax.swing.JLabel jLabel7;
           private javax.swing.JTextField txtCountry;
           private javax.swing.JTextField txtLocation;
           private javax.swing.JTextField txtName;
           private javax.swing.JTextField txtPassword;
           private javax.swing.JTextField txtPostcode;
           private javax.swing.JTextField txtUserName;
           // End of variables declaration//GEN-END:variables
}
