/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BranchRole;

import Business.Business;
import Business.Food.Food;
import Business.Organization.Branch;
import UI.BranchRole.ManageOrder.ManageOrderJPanel;
import UI.BranchRole.ManageStock.ManageStockJPanel;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

import javax.swing.JPanel;

import Business.Business;

/**
 *
 * @author JANFAN
 */
public class BranchWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BranchWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Business business;
    Branch branch;
    Food food;
    /** Creates new form AdminWorkAreaJPanel */
    public BranchWorkAreaJPanel(JPanel userProcessContainer, Business business,Branch branch) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.branch=branch;
        lblName.setText(String.valueOf(branch.getPostcode()));
        txtbname.setText(branch.getName());
        txtnation.setText(branch.getNation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      SplitPanel = new javax.swing.JSplitPane();
                      MenuPanel = new javax.swing.JPanel();
                      btnViewProfile = new javax.swing.JButton();
                      btnManageOrders = new javax.swing.JButton();
                      btnManageStock = new javax.swing.JButton();
                      WorkAreaPanel = new javax.swing.JPanel();
                      lblName = new javax.swing.JLabel();
                      txtbname = new javax.swing.JTextField();
                      lblName2 = new javax.swing.JLabel();
                      lblAge1 = new javax.swing.JLabel();
                      txtnation = new javax.swing.JTextField();
                      btnAddPhoto = new javax.swing.JButton();
                      lblPicture = new javax.swing.JLabel();
                      lblImage = new javax.swing.JLabel();
                      btnUpdate = new javax.swing.JButton();
                      btnSave = new javax.swing.JButton();

                      MenuPanel.setBackground(new java.awt.Color(243, 222, 186));

                      btnViewProfile.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnViewProfile.setText("VIEW PROFILE");
                      btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnViewProfileActionPerformed(evt);
                                 }
                      });

                      btnManageOrders.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnManageOrders.setText("MANAGE ORDERS");
                      btnManageOrders.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnManageOrdersActionPerformed(evt);
                                 }
                      });

                      btnManageStock.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnManageStock.setText("MANAGE STOCK");
                      btnManageStock.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnManageStockActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
                      MenuPanel.setLayout(MenuPanelLayout);
                      MenuPanelLayout.setHorizontalGroup(
                                 MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(MenuPanelLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(MenuPanelLayout.createSequentialGroup()
                                                                  .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                             .addComponent(btnManageOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                                             .addComponent(btnViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                                                  .addGap(0, 0, Short.MAX_VALUE))
                                                       .addComponent(btnManageStock, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                            .addContainerGap())
                      );
                      MenuPanelLayout.setVerticalGroup(
                                 MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(MenuPanelLayout.createSequentialGroup()
                                            .addGap(221, 221, 221)
                                            .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(btnManageOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(btnManageStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(224, Short.MAX_VALUE))
                      );

                      SplitPanel.setLeftComponent(MenuPanel);

                      WorkAreaPanel.setBackground(new java.awt.Color(243, 222, 186));

                      lblName.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      lblName.setText("jLabel2");

                      txtbname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtbname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtbname.setEnabled(false);

                      lblName2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblName2.setText("Name");

                      lblAge1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblAge1.setText("Nation");

                      txtnation.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtnation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtnation.setEnabled(false);

                      btnAddPhoto.setBackground(new java.awt.Color(171, 196, 170));
                      btnAddPhoto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnAddPhoto.setText("PLEASE PRESS THE BUTTON");
                      btnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnAddPhotoActionPerformed(evt);
                                 }
                      });

                      lblPicture.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblPicture.setText("Picture");

                      lblImage.setBackground(new java.awt.Color(204, 204, 0));
                      lblImage.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      btnUpdate.setBackground(new java.awt.Color(103, 93, 80));
                      btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                      btnUpdate.setText("UPDATE");
                      btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnUpdateActionPerformed(evt);
                                 }
                      });

                      btnSave.setBackground(new java.awt.Color(103, 93, 80));
                      btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnSave.setForeground(new java.awt.Color(255, 255, 255));
                      btnSave.setText("SAVE");
                      btnSave.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnSaveActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
                      WorkAreaPanel.setLayout(WorkAreaPanelLayout);
                      WorkAreaPanelLayout.setHorizontalGroup(
                                 WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addGap(129, 129, 129)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                                                  .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(lblName2)
                                                                             .addComponent(lblAge1)
                                                                             .addComponent(lblPicture))
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                  .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                             .addComponent(btnAddPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                             .addComponent(txtnation)
                                                                             .addComponent(txtbname)
                                                                             .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkAreaPanelLayout.createSequentialGroup()
                                                                  .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                  .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addContainerGap(161, Short.MAX_VALUE))
                      );
                      WorkAreaPanelLayout.setVerticalGroup(
                                 WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(lblName)
                                            .addGap(46, 46, 46)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblName2)
                                                       .addComponent(txtbname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(28, 28, 28)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblAge1)
                                                       .addComponent(txtnation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(24, 24, 24)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblPicture)
                                                       .addComponent(btnAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(44, 44, 44)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(82, Short.MAX_VALUE))
                      );

                      SplitPanel.setRightComponent(WorkAreaPanel);

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:

        SplitPanel.setRightComponent(WorkAreaPanel);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrdersActionPerformed
        // TODO add your handling code here:
        ManageOrderJPanel Panel=new ManageOrderJPanel(userProcessContainer, business,branch, SplitPanel);
        SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnManageOrdersActionPerformed

    private void btnManageStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStockActionPerformed
        // TODO add your handling code here:
        ManageStockJPanel Panel=new ManageStockJPanel(business,branch);
        SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnManageStockActionPerformed

           private void btnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhotoActionPerformed
                      // TODO add your handling code here:
                      JFileChooser file = new JFileChooser();
                      file.setCurrentDirectory(new File(System.getProperty("user.home")));
                      FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Image","jpg","png");
                      file.addChoosableFileFilter(filter);
                      int result=file.showSaveDialog(null);
                      if (result==JFileChooser.APPROVE_OPTION){
                                 File selectedFile=file.getSelectedFile();
                                 String path = selectedFile.getAbsolutePath();
                                 ImageIcon MyImage  =new ImageIcon(path);
                                 Image img = MyImage.getImage();
                                 Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                                 ImageIcon image = new ImageIcon(newImg);
                                 lblImage.setIcon(image);
                      }
                      else if (result==JFileChooser.CANCEL_OPTION){
                                 System.out.println("No picture");
                      }
           }//GEN-LAST:event_btnAddPhotoActionPerformed

           private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                      // TODO add your handling code here:
                      txtbname.setEnabled(true);
                      txtnation.setEnabled(true);
           }//GEN-LAST:event_btnUpdateActionPerformed

           private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                      // TODO add your handling code here:
                      String Name = txtbname.getText();
                      String Nation = txtnation.getText();

                      branch.setName(txtbname.getText());
                      branch.setNation(txtnation.getText());
                      branch.setImage((ImageIcon) lblImage.getIcon());
                      JOptionPane.showMessageDialog(this, "The branch profile has been saved.");
           }//GEN-LAST:event_btnSaveActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JPanel MenuPanel;
           private javax.swing.JSplitPane SplitPanel;
           private javax.swing.JPanel WorkAreaPanel;
           private javax.swing.JButton btnAddPhoto;
           private javax.swing.JButton btnManageOrders;
           private javax.swing.JButton btnManageStock;
           private javax.swing.JButton btnSave;
           private javax.swing.JButton btnUpdate;
           private javax.swing.JButton btnViewProfile;
           private javax.swing.JLabel lblAge1;
           private javax.swing.JLabel lblImage;
           private javax.swing.JLabel lblName;
           private javax.swing.JLabel lblName2;
           private javax.swing.JLabel lblPicture;
           private javax.swing.JTextField txtbname;
           private javax.swing.JTextField txtnation;
           // End of variables declaration//GEN-END:variables
}
