/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CompanyRole.ManageStock;

import Business.Business;
import Business.Food.Food;
import Business.Food.FoodCombo;
import Business.Organization.Company;
import Business.Organization.Farm;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class BuyMaterialJPanel extends javax.swing.JPanel {

           /**
            * Creates new form BuyMaterialJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Company company;
           JSplitPane SplitPanel;
           HashMap<FoodCombo, Farm> cart;

           public BuyMaterialJPanel(JPanel userProcessContainer, Business business, Company company, JSplitPane SplitPanel) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.company = company;
                      this.SplitPanel = SplitPanel;
                      cart = new HashMap<>();

                      String farmname = cbFarm.getSelectedItem().toString();
                      for (Farm farm : business.getFarmList()) {
                                 if (farmname.equals(farm.getName())) {
                                            populateFarmTable(farm);
                                            break;
                                 }
                      }

           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        cbFarm = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 222, 186));

        btnBack.setBackground(new java.awt.Color(169, 144, 126));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbFarm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        cbFarm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston Farm", "New York Farm", "Shanghai Farm" }));
        cbFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFarmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Farm:");

        tblMaterial.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Material", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblMaterial);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Amount:");

        txtAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnAdd.setBackground(new java.awt.Color(103, 93, 80));
        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD TO CART");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblCart.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Material", "Farm", "Price", "Amount"
            }
        ));
        tblCart.setPreferredSize(new java.awt.Dimension(230, 80));
        jScrollPane2.setViewportView(tblCart);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Total Cost:");

        lbltotal.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lbltotal.setText("0.0");

        btnCheckOut.setBackground(new java.awt.Color(103, 93, 80));
        btnCheckOut.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckOut.setText("CHECK OUT");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltotal)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbltotal)
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
               // TODO add your handling code here:
               ManageStockJPanel Panel = new ManageStockJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
               // TODO add your handling code here:
               for (Map.Entry<FoodCombo, Farm> set
                                   : cart.entrySet()) {
                          company.addIngerdientStock(set.getKey());
               }

               ManageStockJPanel Panel = new ManageStockJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(Panel);


    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void cbFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFarmActionPerformed
               // TODO add your handling code here:
               String farmname = cbFarm.getSelectedItem().toString();
               for (Farm farm : business.getFarmList()) {
                          if (farmname.equals(farm.getName())) {
                                     populateFarmTable(farm);
                                     break;
                          }
               }
    }//GEN-LAST:event_cbFarmActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
               // TODO add your handling code here:
               String farmname = cbFarm.getSelectedItem().toString();
               Farm farm = null;
               for (Farm f : business.getFarmList()) {
                          if (farmname.equals(f.getName())) {
                                     farm = f;
                                     break;
                          }
               }

               int selectedRowIndex = tblMaterial.getSelectedRow();
               if (selectedRowIndex < 0) {
                          JOptionPane.showMessageDialog(this, "Please select a Material to delete");
                          return;
               }
               DefaultTableModel model = (DefaultTableModel) tblMaterial.getModel();
               Food food = (Food) model.getValueAt(selectedRowIndex, 0);

               int amount = Integer.parseInt(txtAmount.getText());
               FoodCombo fc = new FoodCombo(food, amount);

               cart.put(fc, farm);
               populateCart();


    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JComboBox<String> cbFarm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables

           private void populateFarmTable(Farm farm) {
                      DefaultTableModel model = (DefaultTableModel) tblMaterial.getModel();
                      model.setRowCount(0);

                      for (Map.Entry<Food, Double> set
                                          : farm.getMenu().entrySet()) {
                                 Object[] row = new Object[2];
                                 row[0] = set.getKey();
                                 row[1] = set.getValue();

                                 model.addRow(row);
                      }
           }

           private void populateCart() {
                      DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
                      model.setRowCount(0);
                      double totalprice = 0;
                      for (Map.Entry<FoodCombo, Farm> set
                                          : cart.entrySet()) {
                                 Object[] row = new Object[4];
                                 row[0] = set.getKey().getFood();
                                 row[1] = set.getValue();
                                 row[2] = set.getKey().getFood().getPrice();
                                 row[3] = set.getKey().getNum();
                                 totalprice += (set.getKey().getFood().getPrice() * set.getKey().getNum());

                                 model.addRow(row);
                      }
                      lbltotal.setText(String.valueOf(totalprice));
           }
}
