/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CompanyRole.ManageStock;

import Business.Business;
import Business.Food.Food;
import Business.Food.FoodCombo;
import Business.Organization.Company;
import UI.FarmRole.ManageMenu.CreateMaterialJPanel;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class ManageStockJPanel extends javax.swing.JPanel {

           /**
            * Creates new form ManageStockJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Company company;
           JSplitPane SplitPanel;

           public ManageStockJPanel(JPanel userProcessContainer, Business business, Company company, JSplitPane SplitPanel) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.company = company;
                      this.SplitPanel = SplitPanel;
                      populateProductTable();
                      populateMaterialTable();
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jLabel1 = new javax.swing.JLabel();
                      jScrollPane1 = new javax.swing.JScrollPane();
                      tblProduct = new javax.swing.JTable();
                      jScrollPane2 = new javax.swing.JScrollPane();
                      tblMaterial = new javax.swing.JTable();
                      btnMakeProduct = new javax.swing.JButton();
                      btnBuyMaterial = new javax.swing.JButton();
                      jLabel2 = new javax.swing.JLabel();
                      jLabel3 = new javax.swing.JLabel();

                      setBackground(new java.awt.Color(243, 222, 186));

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("MANAGE STOCK");

                      tblProduct.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblProduct.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null},
                                            {null, null},
                                            {null, null},
                                            {null, null}
                                 },
                                 new String [] {
                                            "Product", "Number"
                                 }
                      ));
                      jScrollPane1.setViewportView(tblProduct);

                      tblMaterial.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null},
                                            {null, null},
                                            {null, null},
                                            {null, null}
                                 },
                                 new String [] {
                                            "Material", "Number"
                                 }
                      ));
                      jScrollPane2.setViewportView(tblMaterial);

                      btnMakeProduct.setBackground(new java.awt.Color(103, 93, 80));
                      btnMakeProduct.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnMakeProduct.setForeground(new java.awt.Color(255, 255, 255));
                      btnMakeProduct.setText("MAKE PRODUCT");
                      btnMakeProduct.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnMakeProductActionPerformed(evt);
                                 }
                      });

                      btnBuyMaterial.setBackground(new java.awt.Color(103, 93, 80));
                      btnBuyMaterial.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnBuyMaterial.setForeground(new java.awt.Color(255, 255, 255));
                      btnBuyMaterial.setText("BUY MATERIAL");
                      btnBuyMaterial.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnBuyMaterialActionPerformed(evt);
                                 }
                      });

                      jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel2.setText("Material Table");

                      jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel3.setText("Product Table");

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addComponent(jLabel3)
                                                                  .addGap(0, 0, Short.MAX_VALUE))
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                             .addGroup(layout.createSequentialGroup()
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                   .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                              .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                   .addGroup(layout.createSequentialGroup()
                                                                                                              .addComponent(btnMakeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                              .addGap(18, 18, 18)
                                                                                                              .addComponent(btnBuyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addGap(0, 45, Short.MAX_VALUE))
                                                                             .addGroup(layout.createSequentialGroup()
                                                                                        .addGap(17, 17, 17)
                                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                  .addContainerGap())))
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnMakeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnBuyMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(9, 9, 9)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(19, Short.MAX_VALUE))
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnBuyMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyMaterialActionPerformed
               // TODO add your handling code here:
               BuyMaterialJPanel Panel = new BuyMaterialJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnBuyMaterialActionPerformed

    private void btnMakeProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeProductActionPerformed
               // TODO add your handling code here:
               int selectedRowIndex = tblProduct.getSelectedRow();
               if (selectedRowIndex < 0) {
                          JOptionPane.showMessageDialog(this, "Please select a food to pruduce");
                          return;
               }
               DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
               Food food = (Food) model.getValueAt(selectedRowIndex, 0);

               //1.find the formula of this food
               //2.check if material is enough for making food 
               //if yes, product +1 material minus
               ArrayList<FoodCombo> materialList = company.getFormula().get(food);
               boolean check = true;
               for (FoodCombo fc : materialList) {
                          check = company.checkIngerdientStock(fc);
                          if (check == false) {
                                     break;
                          }
               }
               if (check == true) {
                          try {
                                     for (FoodCombo fc : materialList) {
                                                company.removeIngerdientStock(fc);
                                     }
                                     FoodCombo product = new FoodCombo(food, 1);
                                     company.addProductStock(product);
                          } catch (Exception e) {
                                     JOptionPane.showMessageDialog(this, "No enough material");
                          }
               }
               populateProductTable();
               populateMaterialTable();

    }//GEN-LAST:event_btnMakeProductActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton btnBuyMaterial;
           private javax.swing.JButton btnMakeProduct;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel2;
           private javax.swing.JLabel jLabel3;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JScrollPane jScrollPane2;
           private javax.swing.JTable tblMaterial;
           private javax.swing.JTable tblProduct;
           // End of variables declaration//GEN-END:variables
    private void populateProductTable() {
                      DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
                      model.setRowCount(0);

                      for (FoodCombo fc : company.getProductStock()) {
                                 Object[] row = new Object[2];
                                 row[0] = fc.getFood();
                                 row[1] = fc.getNum();

                                 model.addRow(row);
                      }

           }

           private void populateMaterialTable() {
                      DefaultTableModel model = (DefaultTableModel) tblMaterial.getModel();
                      model.setRowCount(0);

                      for (FoodCombo fc : company.getIngerdientStock()) {
                                 Object[] row = new Object[2];
                                 row[0] = fc.getFood();
                                 row[1] = fc.getNum();

                                 model.addRow(row);
                      }

           }
}
