/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.FarmRole;

import Business.Business;
import Business.Organization.Farm;
import UI.FarmRole.ManageMenu.ManageMenuJPanel;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author JANFAN
 */
public class FarmWorkAreaJPanel extends javax.swing.JPanel {

           /**
            * Creates new form FarmWorkAreaJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Farm farm;

           /**
            * Creates new form AdminWorkAreaJPanel
            */
           public FarmWorkAreaJPanel(JPanel userProcessContainer, Business business, Farm farm) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.farm = farm;
                      txtfname.setText(farm.getName());
                      txtfusername.setText(farm.getUsername());
                      txtnation.setText(farm.getNation());
                      lblImage.setIcon(farm.getImage());
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      SplitPanel = new javax.swing.JSplitPane();
                      MenuPanel = new javax.swing.JPanel();
                      btnViewProfile = new javax.swing.JButton();
                      btnManageMenu = new javax.swing.JButton();
                      WorkAreaPanel = new javax.swing.JPanel();
                      lblName1 = new javax.swing.JLabel();
                      lblName2 = new javax.swing.JLabel();
                      lblAge1 = new javax.swing.JLabel();
                      lblPicture = new javax.swing.JLabel();
                      txtnation = new javax.swing.JTextField();
                      txtfname = new javax.swing.JTextField();
                      lblName3 = new javax.swing.JLabel();
                      txtfusername = new javax.swing.JTextField();
                      btnAddPhoto = new javax.swing.JButton();
                      lblImage = new javax.swing.JLabel();
                      btnUpdate = new javax.swing.JButton();
                      btnSave = new javax.swing.JButton();

                      MenuPanel.setBackground(new java.awt.Color(243, 222, 186));

                      btnViewProfile.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnViewProfile.setText("VIEW PROFILE");
                      btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnViewProfileActionPerformed(evt);
                                 }
                      });

                      btnManageMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnManageMenu.setText("MANAGE MENU");
                      btnManageMenu.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnManageMenuActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
                      MenuPanel.setLayout(MenuPanelLayout);
                      MenuPanelLayout.setHorizontalGroup(
                                 MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(MenuPanelLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                       .addComponent(btnManageMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                       .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                      );
                      MenuPanelLayout.setVerticalGroup(
                                 MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(MenuPanelLayout.createSequentialGroup()
                                            .addGap(258, 258, 258)
                                            .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnManageMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(264, Short.MAX_VALUE))
                      );

                      SplitPanel.setLeftComponent(MenuPanel);

                      WorkAreaPanel.setBackground(new java.awt.Color(243, 222, 186));

                      lblName1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      lblName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      lblName1.setText("FARM PROFILE");

                      lblName2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblName2.setText("Name");

                      lblAge1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblAge1.setText("Nation");

                      lblPicture.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblPicture.setText("Picture");

                      txtnation.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtnation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtnation.setEnabled(false);

                      txtfname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtfname.setEnabled(false);

                      lblName3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblName3.setText("Username");

                      txtfusername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtfusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtfusername.setEnabled(false);

                      btnAddPhoto.setBackground(new java.awt.Color(171, 196, 170));
                      btnAddPhoto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnAddPhoto.setText("PLEASE PRESS THE BUTTON");
                      btnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnAddPhotoActionPerformed(evt);
                                 }
                      });

                      lblImage.setBackground(new java.awt.Color(204, 204, 0));
                      lblImage.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
                      lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      btnUpdate.setBackground(new java.awt.Color(103, 93, 80));
                      btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                      btnUpdate.setText("UPDATE");
                      btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnUpdateActionPerformed(evt);
                                 }
                      });

                      btnSave.setBackground(new java.awt.Color(103, 93, 80));
                      btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnSave.setForeground(new java.awt.Color(255, 255, 255));
                      btnSave.setText("SAVE");
                      btnSave.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnSaveActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
                      WorkAreaPanel.setLayout(WorkAreaPanelLayout);
                      WorkAreaPanelLayout.setHorizontalGroup(
                                 WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(lblName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addGap(92, 92, 92)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                       .addComponent(lblAge1)
                                                       .addComponent(lblName2)
                                                       .addComponent(lblName3)
                                                       .addComponent(lblPicture))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                  .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                  .addComponent(txtfname)
                                                                  .addComponent(txtfusername)
                                                                  .addComponent(btnAddPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                  .addComponent(txtnation, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                                                  .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                  .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addContainerGap(170, Short.MAX_VALUE))
                      );
                      WorkAreaPanelLayout.setVerticalGroup(
                                 WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(lblName1)
                                            .addGap(73, 73, 73)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblName2)
                                                       .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(txtfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(lblName3))
                                            .addGap(26, 26, 26)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addComponent(txtnation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(lblAge1))
                                            .addGap(18, 18, 18)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblPicture)
                                                       .addComponent(btnAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(62, 62, 62))
                      );

                      SplitPanel.setRightComponent(WorkAreaPanel);

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
               // TODO add your handling code here:
               ManageMenuJPanel Panel = new ManageMenuJPanel(userProcessContainer, business, farm, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnManageMenuActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
               // TODO add your handling code here:

               SplitPanel.setRightComponent(WorkAreaPanel);
    }//GEN-LAST:event_btnViewProfileActionPerformed

           private void btnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhotoActionPerformed
                      // TODO add your handling code here:
                      JFileChooser file = new JFileChooser();
                      file.setCurrentDirectory(new File(System.getProperty("user.home")));
                      FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg", "png");
                      file.addChoosableFileFilter(filter);
                      int result = file.showSaveDialog(null);
                      if (result == JFileChooser.APPROVE_OPTION) {
                                 File selectedFile = file.getSelectedFile();
                                 String path = selectedFile.getAbsolutePath();
                                 ImageIcon MyImage = new ImageIcon(path);
                                 Image img = MyImage.getImage();
                                 Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                                 ImageIcon image = new ImageIcon(newImg);
                                 lblImage.setIcon(image);
                      } else if (result == JFileChooser.CANCEL_OPTION) {
                                 System.out.println("No picture");
                      }
           }//GEN-LAST:event_btnAddPhotoActionPerformed

           private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                      // TODO add your handling code here:
                      String Name = txtfname.getText();
                      String Username = txtfusername.getText();
                      String Nation = txtnation.getText();

                      farm.setName(txtfname.getText());
                      farm.setUsername(txtfusername.getText());
                      farm.setNation(txtnation.getText());
                      farm.setImage((ImageIcon) lblImage.getIcon());
                      JOptionPane.showMessageDialog(this, "The farm profile has been saved.");
           }//GEN-LAST:event_btnSaveActionPerformed

           private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                      // TODO add your handling code here:
                      txtfname.setEnabled(true);
                      txtfusername.setEnabled(true);
                      txtnation.setEnabled(true);
           }//GEN-LAST:event_btnUpdateActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JPanel MenuPanel;
           private javax.swing.JSplitPane SplitPanel;
           private javax.swing.JPanel WorkAreaPanel;
           private javax.swing.JButton btnAddPhoto;
           private javax.swing.JButton btnManageMenu;
           private javax.swing.JButton btnSave;
           private javax.swing.JButton btnUpdate;
           private javax.swing.JButton btnViewProfile;
           private javax.swing.JLabel lblAge1;
           private javax.swing.JLabel lblImage;
           private javax.swing.JLabel lblName1;
           private javax.swing.JLabel lblName2;
           private javax.swing.JLabel lblName3;
           private javax.swing.JLabel lblPicture;
           private javax.swing.JTextField txtfname;
           private javax.swing.JTextField txtfusername;
           private javax.swing.JTextField txtnation;
           // End of variables declaration//GEN-END:variables
}
