/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.FarmRole.ManageMenu;

import Business.Business;
import Business.Food.Food;
import Business.Organization.Farm;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class ManageMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMenuJPanel
     */
    JPanel userProcessContainer;
    Business business;
    Farm farm;
    JSplitPane SplitPanel;
    public ManageMenuJPanel(JPanel userProcessContainer, Business business,Farm farm, JSplitPane SplitPanel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.farm=farm;
        this.SplitPanel=SplitPanel;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jScrollPane1 = new javax.swing.JScrollPane();
                      tblMenu = new javax.swing.JTable();
                      btnCreate = new javax.swing.JButton();
                      btnDelete = new javax.swing.JButton();
                      btnEdit = new javax.swing.JButton();

                      setBackground(new java.awt.Color(243, 222, 186));

                      tblMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblMenu.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null},
                                            {null, null},
                                            {null, null},
                                            {null, null}
                                 },
                                 new String [] {
                                            "Material", "Price"
                                 }
                      ));
                      jScrollPane1.setViewportView(tblMenu);

                      btnCreate.setBackground(new java.awt.Color(103, 93, 80));
                      btnCreate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnCreate.setForeground(new java.awt.Color(255, 255, 255));
                      btnCreate.setText("CREATE");
                      btnCreate.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnCreateActionPerformed(evt);
                                 }
                      });

                      btnDelete.setBackground(new java.awt.Color(103, 93, 80));
                      btnDelete.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnDelete.setForeground(new java.awt.Color(255, 255, 255));
                      btnDelete.setText("DELETE");
                      btnDelete.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnDeleteActionPerformed(evt);
                                 }
                      });

                      btnEdit.setBackground(new java.awt.Color(103, 93, 80));
                      btnEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnEdit.setForeground(new java.awt.Color(255, 255, 255));
                      btnEdit.setText("EDIT");
                      btnEdit.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnEditActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                  .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addGap(105, 105, 105)
                                                                  .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(52, Short.MAX_VALUE))
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(36, 36, 36))
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateMaterialJPanel Panel=new CreateMaterialJPanel( userProcessContainer, business, farm, SplitPanel);
        SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRowIndex=tblMenu.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a Material to delete");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)tblMenu.getModel();
        Food food=(Food)model.getValueAt(selectedRowIndex,0);
        
        farm.getMenu().remove(food);
        //user.deletePerson(selectedPerson);
        JOptionPane.showMessageDialog(this,"Material deleted.");

        populateTable();        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRowIndex=tblMenu.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a Material to view");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)tblMenu.getModel();
        Food food=(Food)model.getValueAt(selectedRowIndex,0);   
        
        EditMaterialJPanel panel=new EditMaterialJPanel(userProcessContainer, business, farm, food,SplitPanel);
        SplitPanel.setRightComponent(panel);
    }//GEN-LAST:event_btnEditActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton btnCreate;
           private javax.swing.JButton btnDelete;
           private javax.swing.JButton btnEdit;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JTable tblMenu;
           // End of variables declaration//GEN-END:variables
private void populateTable() {
        DefaultTableModel model=(DefaultTableModel)tblMenu.getModel();
        model.setRowCount(0);
        
        for(Map.Entry<Food, Double> set :
             farm.getMenu().entrySet()){
            Object[]row =new Object[2];
            row[0]=set.getKey();
            row[1]=set.getValue();

            model.addRow(row);
        }
    }
}
