/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CompanyRole;

import Business.Business;
import Business.Organization.Company;
import UI.CompanyRole.ManageBranch.ManageBranchJPanel;
import UI.CompanyRole.ManageMenu.ManageMenuJPanel;
import UI.CompanyRole.ManageStock.ManageStockJPanel;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author JANFAN
 */
public class CompanyWorkAreaJPanel extends javax.swing.JPanel {

           /**
            * Creates new form CompanyWorkAreaJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Company company;

           /**
            * Creates new form AdminWorkAreaJPanel
            */
           public CompanyWorkAreaJPanel(JPanel userProcessContainer, Business business, Company company) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.company = company;
                      lblName.setText(company.getName());
                      txtcname.setText(company.getName());
                      txtnation.setText(company.getNation());
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      SplitPanel = new javax.swing.JSplitPane();
                      MenuPanel = new javax.swing.JPanel();
                      btnViewProfile = new javax.swing.JButton();
                      btnManageMenu = new javax.swing.JButton();
                      btnManageBranch = new javax.swing.JButton();
                      btnManageStock = new javax.swing.JButton();
                      WorkAreaPanel = new javax.swing.JPanel();
                      btnUpdate = new javax.swing.JButton();
                      btnSave = new javax.swing.JButton();
                      lblName = new javax.swing.JLabel();
                      lblName2 = new javax.swing.JLabel();
                      txtcname = new javax.swing.JTextField();
                      txtnation = new javax.swing.JTextField();
                      lblAge1 = new javax.swing.JLabel();
                      lblPicture = new javax.swing.JLabel();
                      btnAddPhoto = new javax.swing.JButton();
                      lblImage = new javax.swing.JLabel();

                      MenuPanel.setBackground(new java.awt.Color(243, 222, 186));

                      btnViewProfile.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnViewProfile.setText("VIEW PROFILE");
                      btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnViewProfileActionPerformed(evt);
                                 }
                      });

                      btnManageMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnManageMenu.setText("MANAGE MENU");
                      btnManageMenu.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnManageMenuActionPerformed(evt);
                                 }
                      });

                      btnManageBranch.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnManageBranch.setText("MANAGE BRANCH");
                      btnManageBranch.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnManageBranchActionPerformed(evt);
                                 }
                      });

                      btnManageStock.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnManageStock.setText("MANAGE STOCK");
                      btnManageStock.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnManageStockActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
                      MenuPanel.setLayout(MenuPanelLayout);
                      MenuPanelLayout.setHorizontalGroup(
                                 MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(MenuPanelLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                       .addComponent(btnManageMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnManageBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                       .addComponent(btnManageStock, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                      );
                      MenuPanelLayout.setVerticalGroup(
                                 MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                                            .addContainerGap(197, Short.MAX_VALUE)
                                            .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(btnManageBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(btnManageMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(btnManageStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(211, 211, 211))
                      );

                      SplitPanel.setLeftComponent(MenuPanel);

                      WorkAreaPanel.setBackground(new java.awt.Color(243, 222, 186));

                      btnUpdate.setBackground(new java.awt.Color(103, 93, 80));
                      btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                      btnUpdate.setText("UPDATE");
                      btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnUpdateActionPerformed(evt);
                                 }
                      });

                      btnSave.setBackground(new java.awt.Color(103, 93, 80));
                      btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnSave.setForeground(new java.awt.Color(255, 255, 255));
                      btnSave.setText("SAVE");
                      btnSave.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnSaveActionPerformed(evt);
                                 }
                      });

                      lblName.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
                      lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      lblName.setText("jLabel1");

                      lblName2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblName2.setText("Name");

                      txtcname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtcname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtcname.setEnabled(false);

                      txtnation.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtnation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtnation.setEnabled(false);

                      lblAge1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblAge1.setText("Nation");

                      lblPicture.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblPicture.setText("Picture");

                      btnAddPhoto.setBackground(new java.awt.Color(171, 196, 170));
                      btnAddPhoto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnAddPhoto.setText("PLEASE PRESS THE BUTTON");
                      btnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnAddPhotoActionPerformed(evt);
                                 }
                      });

                      lblImage.setBackground(new java.awt.Color(204, 204, 0));
                      lblImage.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
                      WorkAreaPanel.setLayout(WorkAreaPanelLayout);
                      WorkAreaPanelLayout.setHorizontalGroup(
                                 WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addGap(123, 123, 123)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                                                  .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(lblName2)
                                                                             .addComponent(lblAge1)
                                                                             .addComponent(lblPicture))
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                  .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                             .addComponent(btnAddPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                             .addComponent(txtnation)
                                                                             .addComponent(txtcname)
                                                                             .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkAreaPanelLayout.createSequentialGroup()
                                                                  .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                  .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                      );
                      WorkAreaPanelLayout.setVerticalGroup(
                                 WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(63, 63, 63)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblName2)
                                                       .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(28, 28, 28)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblAge1)
                                                       .addComponent(txtnation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(24, 24, 24)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblPicture)
                                                       .addComponent(btnAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(39, 39, 39)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(81, Short.MAX_VALUE))
                      );

                      SplitPanel.setRightComponent(WorkAreaPanel);

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
               // TODO add your handling code here:

               SplitPanel.setRightComponent(WorkAreaPanel);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
               // TODO add your handling code here:
               ManageMenuJPanel Panel = new ManageMenuJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnManageMenuActionPerformed

    private void btnManageBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBranchActionPerformed
               // TODO add your handling code here:
               ManageBranchJPanel Panel = new ManageBranchJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnManageBranchActionPerformed

    private void btnManageStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStockActionPerformed
               // TODO add your handling code here:
               ManageStockJPanel Panel = new ManageStockJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnManageStockActionPerformed

           private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                      // TODO add your handling code here:
                      txtcname.setEnabled(true);
                      txtnation.setEnabled(true);
           }//GEN-LAST:event_btnUpdateActionPerformed

           private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                      // TODO add your handling code here:
                      String Name = txtcname.getText();
                      String Nation = txtnation.getText();

                      company.setName(txtcname.getText());
                      company.setNation(txtnation.getText());
                      company.setImage((ImageIcon) lblImage.getIcon());
                      JOptionPane.showMessageDialog(this, "The company profile has been saved.");
           }//GEN-LAST:event_btnSaveActionPerformed

           private void btnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhotoActionPerformed
                      // TODO add your handling code here:
                      JFileChooser file = new JFileChooser();
                      file.setCurrentDirectory(new File(System.getProperty("user.home")));
                      FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg", "png");
                      file.addChoosableFileFilter(filter);
                      int result = file.showSaveDialog(null);
                      if (result == JFileChooser.APPROVE_OPTION) {
                                 File selectedFile = file.getSelectedFile();
                                 String path = selectedFile.getAbsolutePath();
                                 ImageIcon MyImage = new ImageIcon(path);
                                 Image img = MyImage.getImage();
                                 Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                                 ImageIcon image = new ImageIcon(newImg);
                                 lblImage.setIcon(image);
                      } else if (result == JFileChooser.CANCEL_OPTION) {
                                 System.out.println("No picture");
                      }
           }//GEN-LAST:event_btnAddPhotoActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JPanel MenuPanel;
           private javax.swing.JSplitPane SplitPanel;
           private javax.swing.JPanel WorkAreaPanel;
           private javax.swing.JButton btnAddPhoto;
           private javax.swing.JButton btnManageBranch;
           private javax.swing.JButton btnManageMenu;
           private javax.swing.JButton btnManageStock;
           private javax.swing.JButton btnSave;
           private javax.swing.JButton btnUpdate;
           private javax.swing.JButton btnViewProfile;
           private javax.swing.JLabel lblAge1;
           private javax.swing.JLabel lblImage;
           private javax.swing.JLabel lblName;
           private javax.swing.JLabel lblName2;
           private javax.swing.JLabel lblPicture;
           private javax.swing.JTextField txtcname;
           private javax.swing.JTextField txtnation;
           // End of variables declaration//GEN-END:variables
}
