/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CompanyRole.ManageMenu;

import Business.Business;
import Business.Food.Food;
import Business.Food.FoodCombo;
import Business.Organization.Branch;
import Business.Organization.Company;
import Business.Organization.Farm;
import UI.CompanyRole.ManageStock.ManageStockJPanel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class CreateMenuJPanel extends javax.swing.JPanel {

           /**
            * Creates new form CreateMenuJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Company company;
           JSplitPane SplitPanel;
           HashMap<FoodCombo, Farm> cart;
           double totalprice = 0;

           public CreateMenuJPanel(JPanel userProcessContainer, Business business, Company company, JSplitPane SplitPanel) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.company = company;
                      this.SplitPanel = SplitPanel;
                      cart = new HashMap<>();

                      String farmname = cbFarm.getSelectedItem().toString();
                      for (Farm farm : business.getFarmList()) {
                                 if (farmname.equals(farm.getName())) {
                                            populateFarmTable(farm);
                                            break;
                                 }
                      }
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCreateMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbFarm = new javax.swing.JComboBox<>();
        lbltotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 222, 186));

        tblBack.setBackground(new java.awt.Color(169, 144, 126));
        tblBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblBack.setForeground(new java.awt.Color(255, 255, 255));
        tblBack.setText("<< BACK");
        tblBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblBackActionPerformed(evt);
            }
        });

        tblCreateMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblCreateMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Material", "Farm", "Cost", "Num"
            }
        ));
        jScrollPane1.setViewportView(tblCreateMenu);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Product Name");

        txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Price");

        txtPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnConfirm.setBackground(new java.awt.Color(103, 93, 80));
        btnConfirm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Num");

        txtNum.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblMaterial.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Material", "Cost"
            }
        ));
        jScrollPane2.setViewportView(tblMaterial);

        btnCreate.setBackground(new java.awt.Color(103, 93, 80));
        btnCreate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Total cost:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Material Farm");

        cbFarm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        cbFarm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston Farm", "New York Farm", "Shanghai Farm" }));
        cbFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFarmActionPerformed(evt);
            }
        });

        lbltotal.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lbltotal.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltotal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbFarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbltotal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

           private void tblBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBackActionPerformed
                      // TODO add your handling code here:
                      ManageMenuJPanel Panel = new ManageMenuJPanel(userProcessContainer, business, company, SplitPanel);
                      SplitPanel.setRightComponent(Panel);
           }//GEN-LAST:event_tblBackActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
               // TODO add your handling code here:
               String farmname = cbFarm.getSelectedItem().toString();
               Farm farm = null;
               for (Farm f : business.getFarmList()) {
                          if (farmname.equals(f.getName())) {
                                     farm = f;
                                     break;
                          }
               }

               int selectedRowIndex = tblMaterial.getSelectedRow();
               if (selectedRowIndex < 0) {
                          JOptionPane.showMessageDialog(this, "Please select a Material to delete");
                          return;
               }
               DefaultTableModel model = (DefaultTableModel) tblMaterial.getModel();
               Food food = (Food) model.getValueAt(selectedRowIndex, 0);

               int amount = Integer.parseInt(txtNum.getText());
               FoodCombo fc = new FoodCombo(food, amount);

               cart.put(fc, farm);
               populateCart();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
               // TODO add your handling code here:
               if (txtName.getText().isEmpty() || txtPrice.getText().isEmpty()) {
                          JOptionPane.showMessageDialog(this, "The information is empty!");
               } else {
                          String name = txtName.getText();
                          Double price = Double.parseDouble(txtPrice.getText());

                          Food newfood = new Food(name, totalprice, price);
                          //add to company's menu;
                          company.getMenu().put(newfood, price);
                          //add to company's stock;
                          FoodCombo foodcombo = new FoodCombo(newfood, 0);
                          company.addProductStock(foodcombo);
                          ArrayList<FoodCombo> formula = new ArrayList<>();
                          for (Map.Entry<FoodCombo, Farm> set
                                              : cart.entrySet()) {
                                     formula.add(set.getKey());
                          }
                          company.getFormula().put(newfood, formula);

                          ArrayList<Branch> list = company.getBranchList();
                          for (Branch b : list) {
                                     FoodCombo fc = new FoodCombo(newfood, 0);
                                     b.getStock().add(fc);
                          }
                          JOptionPane.showMessageDialog(this, "new dish created!");
                          ManageMenuJPanel Panel = new ManageMenuJPanel(userProcessContainer, business, company, SplitPanel);
                          SplitPanel.setRightComponent(Panel);

               }


    }//GEN-LAST:event_btnCreateActionPerformed

    private void cbFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFarmActionPerformed
               // TODO add your handling code here:
               String farmname = cbFarm.getSelectedItem().toString();
               for (Farm farm : business.getFarmList()) {
                          if (farmname.equals(farm.getName())) {
                                     populateFarmTable(farm);
                                     break;
                          }
               }
    }//GEN-LAST:event_cbFarmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cbFarm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JButton tblBack;
    private javax.swing.JTable tblCreateMenu;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

           private void populateFarmTable(Farm farm) {
                      DefaultTableModel model = (DefaultTableModel) tblMaterial.getModel();
                      model.setRowCount(0);

                      for (Map.Entry<Food, Double> set
                                          : farm.getMenu().entrySet()) {
                                 Object[] row = new Object[2];
                                 row[0] = set.getKey();
                                 row[1] = set.getValue();

                                 model.addRow(row);
                      }
           }

           private void populateCart() {
                      DefaultTableModel model = (DefaultTableModel) tblCreateMenu.getModel();
                      model.setRowCount(0);
                      totalprice = 0;

                      for (Map.Entry<FoodCombo, Farm> set
                                          : cart.entrySet()) {
                                 Object[] row = new Object[4];
                                 row[0] = set.getKey().getFood();
                                 
                                 row[1] = set.getValue();
                                 row[2]=set.getKey().getFood().getPrice();
                                 row[3] = set.getKey().getNum();
                                 totalprice += (set.getKey().getFood().getPrice() * set.getKey().getNum());

                                 model.addRow(row);
                      }
                      lbltotal.setText(String.valueOf(totalprice));
           }
}
