/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CompanyRole.ManageMenu;

import Business.Business;
import Business.Food.Food;
import Business.Food.FoodCombo;
import Business.Organization.Branch;
import Business.Organization.Company;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class ManageMenuJPanel extends javax.swing.JPanel {

           /**
            * Creates new form ManageMenuJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Company company;
           JSplitPane SplitPanel;

           public ManageMenuJPanel(JPanel userProcessContainer, Business business, Company company, JSplitPane SplitPanel) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.company = company;
                      this.SplitPanel = SplitPanel;
                      populateMenu();
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jLabel1 = new javax.swing.JLabel();
                      jScrollPane1 = new javax.swing.JScrollPane();
                      tblMenu = new javax.swing.JTable();
                      btnCreate = new javax.swing.JButton();
                      btnDelete = new javax.swing.JButton();
                      View = new javax.swing.JButton();

                      setBackground(new java.awt.Color(243, 222, 186));

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("MANAGE MENU");

                      tblMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblMenu.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null},
                                            {null, null},
                                            {null, null},
                                            {null, null}
                                 },
                                 new String [] {
                                            "Product", "Price"
                                 }
                      ));
                      jScrollPane1.setViewportView(tblMenu);

                      btnCreate.setBackground(new java.awt.Color(103, 93, 80));
                      btnCreate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnCreate.setForeground(new java.awt.Color(255, 255, 255));
                      btnCreate.setText("CREATE");
                      btnCreate.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnCreateActionPerformed(evt);
                                 }
                      });

                      btnDelete.setBackground(new java.awt.Color(103, 93, 80));
                      btnDelete.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnDelete.setForeground(new java.awt.Color(255, 255, 255));
                      btnDelete.setText("DELETE");
                      btnDelete.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnDeleteActionPerformed(evt);
                                 }
                      });

                      View.setBackground(new java.awt.Color(103, 93, 80));
                      View.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      View.setForeground(new java.awt.Color(255, 255, 255));
                      View.setText("VIEW");
                      View.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            ViewActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(224, 224, 224)
                                            .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(52, Short.MAX_VALUE))
                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel1)
                                            .addGap(20, 20, 20)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(32, 32, 32))
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
               // TODO add your handling code here:
               CreateMenuJPanel panel = new CreateMenuJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(panel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
               // TODO add your handling code here:

               int selectedRowIndex = tblMenu.getSelectedRow();
               if (selectedRowIndex < 0) {
                          JOptionPane.showMessageDialog(this, "Please select a Product");
                          return;
               }
               DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
               Food food = (Food) model.getValueAt(selectedRowIndex, 0);

               ViewMenuJPanel panel = new ViewMenuJPanel(userProcessContainer, business, company, food, SplitPanel);
               SplitPanel.setRightComponent(panel);
    }//GEN-LAST:event_ViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
               // TODO add your handling code here:
               int selectedRow = tblMenu.getSelectedRow();
               if (selectedRow >= 0) {
                          int dialogButton = JOptionPane.YES_NO_OPTION;
                          int diaogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the menu?", "Warning", dialogButton);
                          if (diaogResult == JOptionPane.YES_NO_OPTION) {
                                     DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
                                     Food food = (Food) model.getValueAt(selectedRow, 0);
                                     company.getFormula().remove(food);
                                     company.getMenu().remove(food);
                                     System.out.println("remove formula");

                                     ArrayList<Branch> list = company.getBranchList();
                                     for (Branch b : list) {
                                                for (FoodCombo fc : b.getStock()) {
                                                           if (fc.getFood() == food) {
                                                                      b.getStock().remove(fc);
                                                                      break;
                                                           }
                                                }
                                     }
                                     for (FoodCombo fc : company.getProductStock()) {
                                                if (fc.getFood() == food) {
                                                           company.getProductStock().remove(fc);
                                                           break;
                                                }
                                     }
                                     populateMenu();
                          } else {
                                     JOptionPane.showMessageDialog(null, "Please select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
                          }
               }


    }//GEN-LAST:event_btnDeleteActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton View;
           private javax.swing.JButton btnCreate;
           private javax.swing.JButton btnDelete;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JTable tblMenu;
           // End of variables declaration//GEN-END:variables

           private void populateMenu() {
                      DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
                      model.setRowCount(0);

                      for (Map.Entry<Food, Double> set
                                          : company.getMenu().entrySet()) {
                                 Object[] row = new Object[2];
                                 row[0] = set.getKey();
                                 row[1] = set.getValue();
                                 model.addRow(row);
                      }
           }
}
