/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CompanyRole.ManageMenu;

import Business.Business;
import Business.Food.Food;
import Business.Food.FoodCombo;
import Business.Organization.Company;
import UI.CompanyRole.ManageStock.ManageStockJPanel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class ViewMenuJPanel extends javax.swing.JPanel {

           /**
            * Creates new form ViewMenuJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Company company;
           Food food;
           JSplitPane SplitPanel;

           public ViewMenuJPanel(JPanel userProcessContainer, Business business, Company company, Food food, JSplitPane SplitPanel) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.company = company;
                      this.food = food;
                      this.SplitPanel = SplitPanel;
                      populate();
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      tblBack = new javax.swing.JButton();
                      txtName = new javax.swing.JTextField();
                      txtPrice = new javax.swing.JTextField();
                      jLabel1 = new javax.swing.JLabel();
                      jLabel2 = new javax.swing.JLabel();
                      btnConfirm = new javax.swing.JButton();
                      btnExit = new javax.swing.JButton();
                      jScrollPane1 = new javax.swing.JScrollPane();
                      tblFormula = new javax.swing.JTable();
                      jLabel3 = new javax.swing.JLabel();

                      setBackground(new java.awt.Color(243, 222, 186));

                      tblBack.setBackground(new java.awt.Color(169, 144, 126));
                      tblBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblBack.setForeground(new java.awt.Color(255, 255, 255));
                      tblBack.setText("<< BACK");
                      tblBack.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            tblBackActionPerformed(evt);
                                 }
                      });

                      txtName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      txtPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel1.setText("Product Name");

                      jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel2.setText("Price");

                      btnConfirm.setBackground(new java.awt.Color(103, 93, 80));
                      btnConfirm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
                      btnConfirm.setText("CONFIRM");
                      btnConfirm.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnConfirmActionPerformed(evt);
                                 }
                      });

                      btnExit.setBackground(new java.awt.Color(103, 93, 80));
                      btnExit.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnExit.setForeground(new java.awt.Color(255, 255, 255));
                      btnExit.setText("EDIT");
                      btnExit.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnExitActionPerformed(evt);
                                 }
                      });

                      tblFormula.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblFormula.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null, null},
                                            {null, null, null},
                                            {null, null, null},
                                            {null, null, null}
                                 },
                                 new String [] {
                                            "Material", "Cost", "Num"
                                 }
                      ));
                      jScrollPane1.setViewportView(tblFormula);

                      jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
                      jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel3.setText("FORMULA");

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGap(18, 18, 18)
                                                                  .addComponent(tblBack))
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGap(50, 50, 50)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                   .addComponent(jLabel1)
                                                                                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                   .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                   .addGap(43, 43, 43)
                                                                                                   .addComponent(jLabel2)
                                                                                                   .addGap(18, 18, 18)
                                                                                                   .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                   .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addContainerGap(49, Short.MAX_VALUE))
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(tblBack)
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(jLabel1)
                                                       .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(jLabel2)
                                                       .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29))
                      );
           }// </editor-fold>//GEN-END:initComponents

           private void tblBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblBackActionPerformed
                      // TODO add your handling code here:
                      ManageMenuJPanel Panel = new ManageMenuJPanel(userProcessContainer, business, company, SplitPanel);
                      SplitPanel.setRightComponent(Panel);
           }//GEN-LAST:event_tblBackActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
               // TODO add your handling code here:
               food.setFoodName(txtName.getText());
               food.setPrice(Double.parseDouble(txtPrice.getText()));
               company.getMenu().put(food, Double.parseDouble(txtPrice.getText()));
               ManageMenuJPanel Panel = new ManageMenuJPanel(userProcessContainer, business, company, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
               // TODO add your handling code here:
               if (txtName.getText().isEmpty() || txtPrice.getText().isEmpty()) {
                          JOptionPane.showMessageDialog(this, "The informatuion is empty");
               } else {
                          food.setFoodName(txtName.getText());
                          food.setPrice(Double.parseDouble(txtPrice.getText()));
                          company.getMenu().put(food, Double.parseDouble(txtPrice.getText()));
                          JOptionPane.showMessageDialog(this, "Food informatuion changed");
               }

    }//GEN-LAST:event_btnExitActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton btnConfirm;
           private javax.swing.JButton btnExit;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel2;
           private javax.swing.JLabel jLabel3;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JButton tblBack;
           private javax.swing.JTable tblFormula;
           private javax.swing.JTextField txtName;
           private javax.swing.JTextField txtPrice;
           // End of variables declaration//GEN-END:variables

           private void populate() {
                      ArrayList<FoodCombo> formular = company.getFormula().get(food);
                      DefaultTableModel model = (DefaultTableModel) tblFormula.getModel();
                      model.setRowCount(0);

                      for (FoodCombo fc : formular) {
                                 Object[] row = new Object[4];
                                 row[0] = fc.toString();
                                 row[1] = fc.getFood().getPrice();
                                 row[2] = fc.getNum();
                                 model.addRow(row);
                      }
                      txtName.setText(food.getFoodName());
                      txtPrice.setText(String.valueOf(food.getPrice()));
           }

}
