/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerRole;

import Business.Business;
import Business.Organization.Customer;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author JANFAN
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

           /**
            * Creates new form CustomerWorkAreaJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Customer customer;
           ImageIcon image;

           /**
            * Creates new form AdminWorkAreaJPanel
            */
           public CustomerWorkAreaJPanel(JPanel userProcessContainer, Business business, Customer customer) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.customer = customer;

                      txtname.setText(customer.getName());
                      txtnation.setText(customer.getNation());
                      lblImage.setIcon(customer.getImage());

           }

           CustomerWorkAreaJPanel() {
                      throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      SplitPanel = new javax.swing.JSplitPane();
                      MenuPanel = new javax.swing.JPanel();
                      btnViewProfile = new javax.swing.JButton();
                      btnViewRestaurant = new javax.swing.JButton();
                      btnViewOrders = new javax.swing.JButton();
                      WorkAreaPanel = new javax.swing.JPanel();
                      lblName1 = new javax.swing.JLabel();
                      btnSave = new javax.swing.JButton();
                      btnUpdate = new javax.swing.JButton();
                      lblName2 = new javax.swing.JLabel();
                      txtname = new javax.swing.JTextField();
                      txtnation = new javax.swing.JTextField();
                      lblAge1 = new javax.swing.JLabel();
                      lblPicture = new javax.swing.JLabel();
                      btnAddPhoto = new javax.swing.JButton();
                      lblImage = new javax.swing.JLabel();

                      MenuPanel.setBackground(new java.awt.Color(243, 222, 186));

                      btnViewProfile.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnViewProfile.setText("VIEW PROFILE");
                      btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnViewProfileActionPerformed(evt);
                                 }
                      });

                      btnViewRestaurant.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnViewRestaurant.setText("VIEW RESTAURANT ");
                      btnViewRestaurant.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnViewRestaurantActionPerformed(evt);
                                 }
                      });

                      btnViewOrders.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnViewOrders.setText("VIEW ORDERS ");
                      btnViewOrders.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnViewOrdersActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
                      MenuPanel.setLayout(MenuPanelLayout);
                      MenuPanelLayout.setHorizontalGroup(
                                 MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(MenuPanelLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(MenuPanelLayout.createSequentialGroup()
                                                                  .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                             .addComponent(btnViewRestaurant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                             .addComponent(btnViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                  .addGap(0, 0, Short.MAX_VALUE))
                                                       .addComponent(btnViewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addContainerGap())
                      );
                      MenuPanelLayout.setVerticalGroup(
                                 MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(MenuPanelLayout.createSequentialGroup()
                                            .addGap(231, 231, 231)
                                            .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(btnViewRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(btnViewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(231, Short.MAX_VALUE))
                      );

                      SplitPanel.setLeftComponent(MenuPanel);

                      WorkAreaPanel.setBackground(new java.awt.Color(243, 222, 186));
                      WorkAreaPanel.setPreferredSize(new java.awt.Dimension(672, 600));

                      lblName1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      lblName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      lblName1.setText("CUSTOMER PROFILE");

                      btnSave.setBackground(new java.awt.Color(103, 93, 80));
                      btnSave.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnSave.setForeground(new java.awt.Color(255, 255, 255));
                      btnSave.setText("SAVE");
                      btnSave.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnSaveActionPerformed(evt);
                                 }
                      });

                      btnUpdate.setBackground(new java.awt.Color(103, 93, 80));
                      btnUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
                      btnUpdate.setText("UPDATE");
                      btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnUpdateActionPerformed(evt);
                                 }
                      });

                      lblName2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblName2.setText("Name");

                      txtname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtname.setEnabled(false);

                      txtnation.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtnation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
                      txtnation.setEnabled(false);

                      lblAge1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblAge1.setText("Nation");

                      lblPicture.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblPicture.setText("Picture");

                      btnAddPhoto.setBackground(new java.awt.Color(171, 196, 170));
                      btnAddPhoto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnAddPhoto.setText("PLEASE PRESS THE BUTTON");
                      btnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnAddPhotoActionPerformed(evt);
                                 }
                      });

                      lblImage.setBackground(new java.awt.Color(204, 204, 0));
                      lblImage.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      javax.swing.GroupLayout WorkAreaPanelLayout = new javax.swing.GroupLayout(WorkAreaPanel);
                      WorkAreaPanel.setLayout(WorkAreaPanelLayout);
                      WorkAreaPanelLayout.setHorizontalGroup(
                                 WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addGap(146, 146, 146)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                       .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                                                  .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                  .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                                                  .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                             .addComponent(lblName2)
                                                                             .addComponent(lblAge1)
                                                                             .addComponent(lblPicture))
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                  .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                             .addComponent(btnAddPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                             .addComponent(txtnation)
                                                                             .addComponent(txtname)
                                                                             .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addContainerGap(195, Short.MAX_VALUE))
                      );
                      WorkAreaPanelLayout.setVerticalGroup(
                                 WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(WorkAreaPanelLayout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(lblName1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblName2)
                                                       .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(28, 28, 28)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblAge1)
                                                       .addComponent(txtnation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(24, 24, 24)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(lblPicture)
                                                       .addComponent(btnAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addGroup(WorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(53, 53, 53))
                      );

                      SplitPanel.setRightComponent(WorkAreaPanel);

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addComponent(SplitPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
               // TODO add your handling code here:

               SplitPanel.setRightComponent(WorkAreaPanel);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnViewRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRestaurantActionPerformed
               // TODO add your handling code here:
               ViewShopJPanel Panel = new ViewShopJPanel(userProcessContainer, business, customer, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnViewRestaurantActionPerformed

    private void btnViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrdersActionPerformed
               // TODO add your handling code here:
               ViewOrderJPanel Panel = new ViewOrderJPanel(userProcessContainer, business, customer, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnViewOrdersActionPerformed

           private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                      // TODO add your handling code here:
                      String Name = txtname.getText();
                      String Nation = txtnation.getText();

                      customer.setName(txtname.getText());
                      customer.setNation(txtnation.getText());
                      customer.setImage((ImageIcon) lblImage.getIcon());
                      JOptionPane.showMessageDialog(this, "The customer profile has been saved.");
           }//GEN-LAST:event_btnSaveActionPerformed

           private void btnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhotoActionPerformed
                      // TODO add your handling code here:
                      JFileChooser file = new JFileChooser();
                      file.setCurrentDirectory(new File(System.getProperty("user.home")));
                      FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg", "png");
                      file.addChoosableFileFilter(filter);
                      int result = file.showSaveDialog(null);
                      if (result == JFileChooser.APPROVE_OPTION) {
                                 File selectedFile = file.getSelectedFile();
                                 String path = selectedFile.getAbsolutePath();
                                 ImageIcon MyImage = new ImageIcon(path);
                                 Image img = MyImage.getImage();
                                 Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                                 ImageIcon image = new ImageIcon(newImg);
                                 lblImage.setIcon(image);
                      } else if (result == JFileChooser.CANCEL_OPTION) {
                                 System.out.println("No picture");
                      }
           }//GEN-LAST:event_btnAddPhotoActionPerformed

           private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                      // TODO add your handling code here:
                      txtname.setEnabled(true);
                      txtnation.setEnabled(true);
           }//GEN-LAST:event_btnUpdateActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JPanel MenuPanel;
           private javax.swing.JSplitPane SplitPanel;
           private javax.swing.JPanel WorkAreaPanel;
           private javax.swing.JButton btnAddPhoto;
           private javax.swing.JButton btnSave;
           private javax.swing.JButton btnUpdate;
           private javax.swing.JButton btnViewOrders;
           private javax.swing.JButton btnViewProfile;
           private javax.swing.JButton btnViewRestaurant;
           private javax.swing.JLabel lblAge1;
           private javax.swing.JLabel lblImage;
           private javax.swing.JLabel lblName1;
           private javax.swing.JLabel lblName2;
           private javax.swing.JLabel lblPicture;
           private javax.swing.JTextField txtname;
           private javax.swing.JTextField txtnation;
           // End of variables declaration//GEN-END:variables
}
