/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerRole;

import Business.Business;
import Business.Food.Food;
import Business.Food.FoodCombo;
import Business.Order.Order;
import Business.Organization.Branch;
import Business.Organization.Customer;
import Business.Organization.Farm;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Map;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class ShoopingCartJPanel extends javax.swing.JPanel {

           /**
            * Creates new form ShoopingCartJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Customer customer;
           JSplitPane SplitPanel;
           Branch branch;
           boolean isPrime = false;
           ArrayList<FoodCombo> cart;

           public ShoopingCartJPanel(JPanel userProcessContainer, Business business, Customer customer, Branch branch, JSplitPane SplitPanel) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.customer = customer;
                      this.SplitPanel = SplitPanel;
                      this.branch = branch;
                      cart = new ArrayList<>();

                      ArrayList<Customer> membershipList = branch.getCompany().getPrimeList();
                      for (Customer c : membershipList) {
                                 if (c == customer) {
                                            isPrime = true;
                                 }
                      }
                      if (isPrime == true) {
                                 btnMembership.setEnabled(false);
                      }
                      populate();

           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblshoppingCart = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblshopping = new javax.swing.JTable();
        btncheckOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        lbltotalmark = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        btnMembership = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 222, 186));

        btnBack.setBackground(new java.awt.Color(169, 144, 126));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblshoppingCart.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblshoppingCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Food", "Price", "Num"
            }
        ));
        jScrollPane1.setViewportView(tblshoppingCart);

        tblshopping.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tblshopping.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Food", "Price"
            }
        ));
        jScrollPane2.setViewportView(tblshopping);

        btncheckOut.setBackground(new java.awt.Color(103, 93, 80));
        btncheckOut.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btncheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btncheckOut.setText("CHECK OUT");
        btncheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckOutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Num:");

        btnadd.setBackground(new java.awt.Color(103, 93, 80));
        btnadd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("ADD TO CART");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        txtNum.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbltotalmark.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lbltotalmark.setText("Total:");

        lbltotal.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lbltotal.setText("0.0");

        btnMembership.setBackground(new java.awt.Color(103, 93, 80));
        btnMembership.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnMembership.setForeground(new java.awt.Color(255, 255, 255));
        btnMembership.setText("Become Membership");
        btnMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembershipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(btnBack))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltotalmark)
                                .addGap(18, 18, 18)
                                .addComponent(lbltotal)
                                .addGap(18, 18, 18)
                                .addComponent(btncheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMembership, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltotalmark)
                    .addComponent(lbltotal))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

           private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                      // TODO add your handling code here:
                      ViewShopJPanel Panel = new ViewShopJPanel(userProcessContainer, business, customer, SplitPanel);
                      SplitPanel.setRightComponent(Panel);
           }//GEN-LAST:event_btnBackActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
               // TODO add your handling code here:
               int selectedRowIndex = tblshopping.getSelectedRow();
               if (selectedRowIndex < 0) {
                          JOptionPane.showMessageDialog(this, "Please select a Material to delete");
                          return;
               }
               DefaultTableModel model = (DefaultTableModel) tblshopping.getModel();
               Food food = (Food) model.getValueAt(selectedRowIndex, 0);

               for (FoodCombo f : cart) {
                          if (f.getFood() == food) {
                                     f.setNum(f.getNum() + Integer.parseInt(txtNum.getText()));
                                     populateCart();
                                     return;
                          }

               }

               FoodCombo fc = new FoodCombo(food, Integer.parseInt(txtNum.getText()));
               cart.add(fc);
               populateCart();


    }//GEN-LAST:event_btnaddActionPerformed

    private void btncheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckOutActionPerformed
               // TODO add your handling code here:
               Random r = new Random(System.currentTimeMillis());
               int id = ((1 + r.nextInt(2)) * 10000 + r.nextInt(10000));
               Order order = customer.getOrderDir().createOrder(cart, Double.parseDouble(lbltotal.getText()), "b" + String.valueOf(id), customer, branch, "uncomplete");
               branch.getOrderDir().addOrder(order);
               ViewOrderJPanel Panel = new ViewOrderJPanel(userProcessContainer, business, customer, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btncheckOutActionPerformed

    private void btnMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMembershipActionPerformed
               // TODO add your handling code here:
               //use the list in company to find if the customer is a membership
               int dialogButton = JOptionPane.YES_NO_OPTION;
               int diaogResult = JOptionPane.showConfirmDialog(null, "Would you like to updrade to membership? It costs" + branch.getCompany().getMembershpPrice(), "Warning", dialogButton);
               if (diaogResult == JOptionPane.YES_NO_OPTION) {
                          branch.getCompany().getPrimeList().add(customer);
                          isPrime = true;
                          btnMembership.setEnabled(false);
                          branch.getCompany().setAsset(branch.getCompany().getAsset() + branch.getCompany().getMembershpPrice());
                          populateCart();
               }

    }//GEN-LAST:event_btnMembershipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMembership;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel lbltotalmark;
    private javax.swing.JTable tblshopping;
    private javax.swing.JTable tblshoppingCart;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables

           private void populate() {
                      DefaultTableModel model = (DefaultTableModel) tblshopping.getModel();
                      model.setRowCount(0);

                      for (FoodCombo fc : branch.getStock()) {
                                 Object[] row = new Object[2];
                                 row[0] = fc.getFood();
                                 row[1] = fc.getFood().getPrice();

                                 model.addRow(row);
                      }
           }

           private void populateCart() {
                      DefaultTableModel model = (DefaultTableModel) tblshoppingCart.getModel();
                      model.setRowCount(0);
                      double totalprice = 0;
                      for (FoodCombo fc : cart) {
                                 Object[] row = new Object[3];
                                 row[0] = fc.getFood();
                                 row[1] = fc.getFood().getPrice();
                                 row[2] = fc.getNum();

                                 totalprice += (fc.getFood().getPrice() * fc.getNum());

                                 model.addRow(row);
                      }
                      if (isPrime == false) {
                                 lbltotal.setText(String.valueOf(totalprice));
                      } else {
                                 lbltotalmark.setText("Membership price:");
                                 lbltotal.setText(String.valueOf(totalprice * branch.getCompany().getDiscount()));
                      }
           }
}
