/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CustomerRole;

import Business.Business;
import Business.Food.Food;
import Business.Organization.Account;
import Business.Organization.Branch;
import Business.Organization.Company;
import Business.Organization.Customer;
import Business.Rule.Role;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JANFAN
 */
public class ViewShopJPanel extends javax.swing.JPanel {

           /**
            * Creates new form ViewShopJPanel
            */
           JPanel userProcessContainer;
           Business business;
           Customer customer;
           JSplitPane SplitPanel;
           Company company;

           public ViewShopJPanel(JPanel userProcessContainer, Business business, Customer customer, JSplitPane SplitPanel) {
                      initComponents();
                      this.userProcessContainer = userProcessContainer;
                      this.business = business;
                      this.customer = customer;
                      this.SplitPanel = SplitPanel;

                      populateViewShopTable();
           }

           /**
            * This method is called from within the constructor to initialize the form. WARNING: Do
            * NOT modify this code. The content of this method is always regenerated by the Form
            * Editor.
            */
           @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jScrollPane1 = new javax.swing.JScrollPane();
                      tblviewShop = new javax.swing.JTable();
                      btnNext = new javax.swing.JButton();
                      btnSearch = new javax.swing.JButton();
                      jLabel1 = new javax.swing.JLabel();
                      jLabel2 = new javax.swing.JLabel();
                      txtCountry = new javax.swing.JTextField();
                      txtLocation = new javax.swing.JTextField();

                      setBackground(new java.awt.Color(243, 222, 186));

                      tblviewShop.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblviewShop.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null, null},
                                            {null, null, null},
                                            {null, null, null},
                                            {null, null, null}
                                 },
                                 new String [] {
                                            "Name", "Country", "Location"
                                 }
                      ));
                      jScrollPane1.setViewportView(tblviewShop);

                      btnNext.setBackground(new java.awt.Color(103, 93, 80));
                      btnNext.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnNext.setForeground(new java.awt.Color(255, 255, 255));
                      btnNext.setText("NEXT");
                      btnNext.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnNextActionPerformed(evt);
                                 }
                      });

                      btnSearch.setBackground(new java.awt.Color(103, 93, 80));
                      btnSearch.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnSearch.setForeground(new java.awt.Color(255, 255, 255));
                      btnSearch.setText("SEARCH");
                      btnSearch.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnSearchActionPerformed(evt);
                                 }
                      });

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel1.setText("Country");

                      jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      jLabel2.setText("Location");

                      txtCountry.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtCountry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      txtLocation.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      txtLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addContainerGap(46, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addComponent(jLabel1)
                                                                  .addGap(18, 18, 18)
                                                                  .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addGap(60, 60, 60)
                                                                  .addComponent(jLabel2)
                                                                  .addGap(18, 18, 18)
                                                                  .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addGap(22, 22, 22)
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                             .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                             .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                       .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(50, Short.MAX_VALUE))
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(jLabel1)
                                                       .addComponent(jLabel2)
                                                       .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36))
                      );
           }// </editor-fold>//GEN-END:initComponents

           private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                      populateSearchRestaurantTable(txtCountry.getText(), txtLocation.getText());

           }//GEN-LAST:event_btnSearchActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
               // TODO add your handling code here:
               int selectedRowIndex = tblviewShop.getSelectedRow();
               if (selectedRowIndex < 0) {
                          JOptionPane.showMessageDialog(this, "Please select a resturant to view");
                          return;
               }
               DefaultTableModel model = (DefaultTableModel) tblviewShop.getModel();
               Branch branch = (Branch) model.getValueAt(selectedRowIndex, 0);

               ShoopingCartJPanel Panel = new ShoopingCartJPanel(userProcessContainer, business, customer, branch, SplitPanel);
               SplitPanel.setRightComponent(Panel);
    }//GEN-LAST:event_btnNextActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton btnNext;
           private javax.swing.JButton btnSearch;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel2;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JTable tblviewShop;
           private javax.swing.JTextField txtCountry;
           private javax.swing.JTextField txtLocation;
           // End of variables declaration//GEN-END:variables

           private void populateViewShopTable() {
                      DefaultTableModel model = (DefaultTableModel) tblviewShop.getModel();
                      model.setRowCount(0);

                      for (Branch b : business.getBranchList()) {
                                 Object[] row = new Object[3];
                                 row[0] = b;
                                 row[1] = b.getNation();
                                 row[2] = b.getLocation();
                                 model.addRow(row);
                      }
           }

           private void populateSearchRestaurantTable(String country, String location) {
                      DefaultTableModel model = (DefaultTableModel) tblviewShop.getModel();
                      model.setRowCount(0);
                      ArrayList<Branch> tempList = new ArrayList<>();
                      //System.out.println(tempList.toString());
                      tempList = bWithCountry(tempList, country);
                      //System.out.println(tempList.toString());
                      tempList = bWithLocation(tempList, location);
                      //System.out.println(tempList.toString());

                      for (Branch b : tempList) {
                                 Object[] row = new Object[3];
                                 row[0] = b;
                                 row[1] = b.getNation();
                                 row[2] = b.getLocation();

                                 model.addRow(row);
                      }
           }

           private ArrayList<Branch> bWithCountry(ArrayList<Branch> plist, String country) {
                      if (country == null || country.equals("")) {
                                 plist.addAll(business.getBranchList());
                                 //System.out.println("name pass");

                                 return plist;
                      }
                      for (Branch b : business.getBranchList()) {
                                 if (b.getNation().equals(country)) {
                                            plist.add(b);
                                 }
                      }

                      return plist;
           }

           private ArrayList<Branch> bWithLocation(ArrayList<Branch> plist, String location) {
                      if (location == null || location.equals("")) {
                                 //plist.addAll(company.getBranchList());
                                 //System.out.println("name pass");
                                 return plist;
                      }
                      for (int i = 0; i < plist.size(); i++) {

                                 if (!plist.get(i).getLocation().equals(location)) {
                                            plist.remove(plist.get(i));
                                            i -= 1;
                                 }
                      }
                      return plist;
           }

}
