/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BranchRole.ManageOrder;

/**
 *
 * @author JANFAN
 */

import Business.Business;
import Business.Food.FoodCombo;
import Business.Order.Order;
import Business.Organization.Branch;
import UI.BranchRole.ManageOrder.ManageOrderJPanel;
import UI.BranchRole.ManageStock.ManageStockJPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
public class ManageOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderJPanel
     */
    
    JPanel userProcessContainer;
    Business business;
    Branch branch;
    JSplitPane SplitPanel;
    Order order;
    public ManageOrderJPanel(JPanel userProcessContainer, Business business,Branch branch,JSplitPane SplitPanel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.branch = branch;
        this.SplitPanel=SplitPanel;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      jLabel1 = new javax.swing.JLabel();
                      jScrollPane1 = new javax.swing.JScrollPane();
                      tblOrder = new javax.swing.JTable();
                      btnProcess = new javax.swing.JButton();
                      btnOrderHistory = new javax.swing.JButton();

                      setBackground(new java.awt.Color(243, 222, 186));

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("PENDING ORDER");

                      tblOrder.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblOrder.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null, null},
                                            {null, null, null},
                                            {null, null, null},
                                            {null, null, null}
                                 },
                                 new String [] {
                                            "Order ID", "Price", "Status"
                                 }
                      ));
                      jScrollPane1.setViewportView(tblOrder);

                      btnProcess.setBackground(new java.awt.Color(103, 93, 80));
                      btnProcess.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnProcess.setForeground(new java.awt.Color(255, 255, 255));
                      btnProcess.setText("PROCESS");
                      btnProcess.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnProcessActionPerformed(evt);
                                 }
                      });

                      btnOrderHistory.setBackground(new java.awt.Color(103, 93, 80));
                      btnOrderHistory.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnOrderHistory.setForeground(new java.awt.Color(255, 255, 255));
                      btnOrderHistory.setText("ORDER HISTORY");
                      btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnOrderHistoryActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(160, 160, 160)
                                            .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(42, 42, 42)
                                            .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 44, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(50, Short.MAX_VALUE))
                                 .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel1)
                                            .addGap(20, 20, 20)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addContainerGap(23, Short.MAX_VALUE))
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex=tblOrder.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a Order to view");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)tblOrder.getModel();
        Order order1=(Order)model.getValueAt(selectedRowIndex,0);   
        ProcesOrderJPanel pane = new ProcesOrderJPanel(userProcessContainer, business,branch, order1, SplitPanel);
        SplitPanel.setRightComponent(pane);
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        // TODO add your handling code here:
        OrderHistoryJPanel pane = new OrderHistoryJPanel(userProcessContainer, business,branch, SplitPanel);
        SplitPanel.setRightComponent(pane);
    }//GEN-LAST:event_btnOrderHistoryActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton btnOrderHistory;
           private javax.swing.JButton btnProcess;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JTable tblOrder;
           // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model=(DefaultTableModel)tblOrder.getModel();
        model.setRowCount(0);
        
        for(Order odr : branch.getOrderDir().getOrderList()){
            if("uncomplete".equals(odr.getStatus())){
                Object[]row =new Object[3];
                row[0]=odr;
                row[1]=odr.getTotalPrice();
                row[2]=odr.getStatus();

                model.addRow(row);
            }
        }
    }
}
