/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BranchRole.ManageOrder;

/**
 *
 * @author JANFAN
 */
import Business.Business;
import Business.Food.FoodCombo;
import Business.Order.Order;
import Business.Organization.Branch;
import UI.BranchRole.ManageOrder.ManageOrderJPanel;
import UI.BranchRole.ManageStock.ManageStockJPanel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
public class ProcesOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcesOrderJPanel
     */
    JPanel userProcessContainer;
    Business business;
    Branch branch;
    JSplitPane SplitPanel;
    Order order;
    public ProcesOrderJPanel(JPanel userProcessContainer, Business business,Branch branch, Order order,JSplitPane SplitPanel) {
        initComponents();
        this.order = order;
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.branch = branch;
        this.SplitPanel=SplitPanel;
        populateTable1();
        populateTable2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
           // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
           private void initComponents() {

                      btnBack = new javax.swing.JButton();
                      jScrollPane1 = new javax.swing.JScrollPane();
                      tblProduct = new javax.swing.JTable();
                      jScrollPane2 = new javax.swing.JScrollPane();
                      tblStock = new javax.swing.JTable();
                      jLabel1 = new javax.swing.JLabel();
                      jLabel2 = new javax.swing.JLabel();
                      btnRefuse = new javax.swing.JButton();
                      btnConfirm = new javax.swing.JButton();

                      setBackground(new java.awt.Color(243, 222, 186));

                      btnBack.setBackground(new java.awt.Color(169, 144, 126));
                      btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnBack.setForeground(new java.awt.Color(255, 255, 255));
                      btnBack.setText("<< BACK");
                      btnBack.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnBackActionPerformed(evt);
                                 }
                      });

                      tblProduct.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblProduct.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null, null},
                                            {null, null, null},
                                            {null, null, null},
                                            {null, null, null}
                                 },
                                 new String [] {
                                            "Product", "Price", "Num"
                                 }
                      ));
                      jScrollPane1.setViewportView(tblProduct);

                      tblStock.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      tblStock.setModel(new javax.swing.table.DefaultTableModel(
                                 new Object [][] {
                                            {null, null},
                                            {null, null},
                                            {null, null},
                                            {null, null}
                                 },
                                 new String [] {
                                            "Product", "Num"
                                 }
                      ));
                      jScrollPane2.setViewportView(tblStock);

                      jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
                      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel1.setText("ORDER DETAIL");

                      jLabel2.setBackground(new java.awt.Color(243, 222, 186));
                      jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
                      jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                      jLabel2.setText("STOCK");

                      btnRefuse.setBackground(new java.awt.Color(103, 93, 80));
                      btnRefuse.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnRefuse.setForeground(new java.awt.Color(255, 255, 255));
                      btnRefuse.setText("REFUSE");
                      btnRefuse.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnRefuseActionPerformed(evt);
                                 }
                      });

                      btnConfirm.setBackground(new java.awt.Color(103, 93, 80));
                      btnConfirm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
                      btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
                      btnConfirm.setText("CONFIRM");
                      btnConfirm.addActionListener(new java.awt.event.ActionListener() {
                                 public void actionPerformed(java.awt.event.ActionEvent evt) {
                                            btnConfirmActionPerformed(evt);
                                 }
                      });

                      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                      this.setLayout(layout);
                      layout.setHorizontalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                             .addGroup(layout.createSequentialGroup()
                                                                                        .addGap(165, 165, 165)
                                                                                        .addComponent(btnRefuse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(109, 109, 109)
                                                                                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                        .addGap(44, 44, 44)
                                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                  .addGap(0, 0, Short.MAX_VALUE))
                                                       .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                       .addGroup(layout.createSequentialGroup()
                                                                  .addGap(49, 49, 49)
                                                                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addContainerGap())
                                 .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                      );
                      layout.setVerticalGroup(
                                 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap(20, Short.MAX_VALUE)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                       .addComponent(btnRefuse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(12, 12, 12))
                      );
           }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        Boolean isok = false;
        ArrayList<FoodCombo> temp = new ArrayList<>();
        for(FoodCombo cmb : order.getFoodCombo()){
            for(FoodCombo b_cmb : branch.getStock()){
                if(cmb.getFood() == b_cmb.getFood()){
                    if(cmb.getNum() <= b_cmb.getNum()){
                        FoodCombo temp_cmb = new FoodCombo(cmb.getFood(), b_cmb.getNum() - cmb.getNum());
                        temp.add(temp_cmb);
                        isok = true;
                    }else{
                            isok = false;
                        }
                    }
                }
            }
        if(isok == true){
            for(FoodCombo b_cmb : branch.getStock()){
                for(FoodCombo temp_cmb : temp){
                    if(b_cmb.getFood() == temp_cmb.getFood()){
                        b_cmb.setNum(temp_cmb.getNum());
                    }
                }
            }
            JOptionPane.showMessageDialog(this,"successfully dealing the order");
            order.setStatus("Complete");
            branch.setAsset(branch.getAsset() + order.getTotalPrice());
        }else{
            JOptionPane.showMessageDialog(this,"not enough in stock");
            order.setStatus("Canceled");
        }
        btnRefuse.setEnabled(false);
        btnConfirm.setEnabled(false);
        populateTable2();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnRefuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefuseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"successfully cancel the order");
        order.setStatus("Canceled");
        btnRefuse.setEnabled(false);
        btnConfirm.setEnabled(false);
    }//GEN-LAST:event_btnRefuseActionPerformed

           private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                      // TODO add your handling code here:
          ManageOrderJPanel MOPanel = new ManageOrderJPanel(userProcessContainer, business, branch, SplitPanel);
          SplitPanel.setRightComponent(MOPanel);
           }//GEN-LAST:event_btnBackActionPerformed


           // Variables declaration - do not modify//GEN-BEGIN:variables
           private javax.swing.JButton btnBack;
           private javax.swing.JButton btnConfirm;
           private javax.swing.JButton btnRefuse;
           private javax.swing.JLabel jLabel1;
           private javax.swing.JLabel jLabel2;
           private javax.swing.JScrollPane jScrollPane1;
           private javax.swing.JScrollPane jScrollPane2;
           private javax.swing.JTable tblProduct;
           private javax.swing.JTable tblStock;
           // End of variables declaration//GEN-END:variables

    private void populateTable1() {
        DefaultTableModel model=(DefaultTableModel)tblProduct.getModel();
        model.setRowCount(0);
        for(FoodCombo cmb : order.getFoodCombo()){
            Object[]row =new Object[3];
            row[0]=cmb.getFood();
            row[1]=cmb.getFood().getPrice();
            row[2]=cmb.getNum();

            model.addRow(row);
            }
        }        

    private void populateTable2() {
        DefaultTableModel model=(DefaultTableModel)tblStock.getModel();
        model.setRowCount(0);
        
        for(FoodCombo cmb : branch.getStock()){
            Object[]row =new Object[2];
            row[0]=cmb.getFood();
            row[1]=cmb.getNum();

            model.addRow(row);
        }
    }
    }

